### ISSUE TITLE
WP CLI does not work once activated.

### ISSUE THREAD

**Issue by advwebin** [thegulshankumar/edge-caching-firewall-bunnycdn#1]
Hi Gulshan,

I have been looking for a plugin for Bunny CDN and came across this, I wanted to thank you for the plugin, works well out of the box.

I found an issue, updating using CLI is no longer possible when using this plugin. Is there a fix for this or are you actively working on this?

Is there a way to set cache policy and make sure edge cache TTL can be changed using settings?

Thanks

**Comment by thegulshankumar** [comment]
This plugin isn't listed at WP repo. Hence, you cannot update via WP CLI.

**Comment by thegulshankumar** [comment]
Note: -This plugin is no longer maintained by me. Please do not expect any update on this. Thank you for understanding.

**Comment by advwebin** [comment]
> This plugin isn't listed at WP repo. Hence, you cannot update via WP CLI.

@thegulshankumar I am aware this is not on WP Repo, I had issues with CLI completely once the plugin was activated and setup. I couldn't use ANY COMMAND on WP CLI. wp plugin list also won't work.

Any clue on whats causing this?

Thank you
